### ISSUE TITLE
Rebuild-DNDC NetModeID doesn't match with binhex-delugevpn ContID

### ISSUE THREAD

**Issue by jakemoura** [elmerfdz/unRAIDscripts#49]
Running across this issue today on unraid. Master container name is "binhex-delugevpn" and docker network name is "binhex-delugevpn". Don't really see what I configed wrong. Container stops after the last line. 

Heres the full log: 
----------------------------------------------------
[------------------ CONFIG CHECK ------------------]

- Discord webhook not set
- Discord notifications disabled
- Master container name set: binhex-delugevpn
- Ping count specified: 4
- Ping IP specified: 1.1.1.1
- Ping IP alt set: 8.8.8.8
- Master container connectivity check enabled
- Sleep secs set: 10
- CRON schedule set: */5 * * * *
- Save no of master cotnainer IDs, default - 5
- No containers set for manual run
/etc/cont-init.d/30-install: line 119: =none: not found
- Run at startup: yes
- CRON job has been set
- Running at startup now...

---------------------------------
Rebuild-DNDC v4.0.6-u
---------------------------------

-----------------------------------------------------------------------------------
# MASTER CONTAINER INFO
- CONTAINER-NAME: binhex-delugevpn
- ENDPOINT-ID:
- NETMODE-ID: 148c24d45c290ac02ce33c145159c50afb6564de989b9351398b1212fff0a7fb
- CONNECTIVITY: OK
-----------------------------------------------------------------------------------

A. SKIPPING: FIRST RUN SETUP
B. SKIPPING: MASTER CONTAINER ENDPOINTID IS CURRENT
C. DETECTING: IN-SCOPE CONTAINERS

# RESULTS: None in-scope, checking for previous in-scope containers

D. PROCESSING: IN-SCOPE CONTAINERS

- Rebuild-DNDC NetModeID doesn't match with binhex-delugevpn ContID

----------------------------
Stopping: Rebuild-DNDC
----------------------------

**Comment by elmerfds** [comment]
Hi there,

- Is the binhex-delugevpn container already running & connected before you start rebuild-dndc? 
- Could you please post a screenshot of your rebuild-dndc container template?
- Unraid version?

**Comment by jakemoura** [comment]
You know I just figured it out today. I forgot I created a new docker network for my deluge and some other apps (ie: proxy). I changed rebuild-dndc to the new network (in this case proxy) and everything seems to be working. 

I should have read the error more closely... 

Thanks for the response going to close!

**Comment by jakemoura** [comment]
Oop... Reopening. 

Same error: Rebuild-DNDC NetModeID doesn't match with binhex-delugevpn ContID

Going thorough your questions: 

- Yes delugevpn is running before rebuild is running
- https://i.imgur.com/zTlZaTM.png
- Unraid version 6.9 rc2

**Comment by elmerfds** [comment]
Think there might be an issue with your docker network setup.

Can you try changing the network type of the rebuild container to bridge or host and see if it makes any difference?

**Comment by jakemoura** [comment]
Changed to host and bridge and still get the same error: 

# MASTER CONTAINER INFO
- CONTAINER-NAME: binhex-delugevpn
- ENDPOINT-ID:
- NETMODE-ID: af06e3ca78f888b3e38390c40bacc185ffc002f5116e1c1fd3f61af1dac886ce
- CONNECTIVITY: OK
-----------------------------------------------------------------------------------

A. SKIPPING: FIRST RUN SETUP
B. SKIPPING: MASTER CONTAINER ENDPOINTID IS CURRENT
C. DETECTING: IN-SCOPE CONTAINERS

# RESULTS: None in-scope, checking for previous in-scope containers

D. PROCESSING: IN-SCOPE CONTAINERS


- Rebuild-DNDC NetModeID doesn't match with binhex-delugevpn ContID

----------------------------
Stopping: Rebuild-DNDC
----------------------------

**Comment by elmerfds** [comment]
"**Rebuild-DNDC NetModeID doesn't match with binhex-delugevpn ContID**" this bit shouldn't be happening, for some reason it has detected itself as an in-scope container of your vpn network, probably a remnant of a previous incorrect config?

Open /config/rebuild-dndc/list_inscope_cont_names.tmp file and check if rebuild-dndc is listed on there. If it is, then delete the following files:
list_inscope_cont_ids.tmp
list_inscope_cont_names.tmp

If it isn't listed, just delete all .tmp files and restart rebuild.

**Comment by jakemoura** [comment]
That fixed it! I had an old ssd with my appdata that died. Guess it had my old config on it...

Thanks so much!
