### ISSUE TITLE
docker network create in Unraid 6.7.2 on a container with capitalization

### ISSUE THREAD

**Issue by JesterEE** [elmerfdz/unRAIDscripts#5]
Following the prerequisite instructions in the README on an Unraid 6.7.2 server.  Doing the first step (i.e. ```docker network create container:master_container_name```) works, but if the ```container:master_container_name``` has any capitalization, applying the network to other dockers will result in failed ```docker create``` execution.  When inspecting the log output, it looks like Unraid is lower casing the ```master_container_name``` (i.e. ```container:ABCVPN``` results in a ```--net='container:abcvpn'``` command line argument).

This is not a docker image problem, though it affects the use of the image so I wanted to report it here so the documentation can be revised to reflect the Unraid issue in the 6.7 version series.

**Comment by elmerfds** [comment]
Thanks! I had noticed that but forgot to add it to the readme & it's the same on 6.8.x builds . I usually capitalise the first letter of my docker containers, had to rename the master container to lower case :(
