### ISSUE TITLE
notifications from GOTIFY

### ISSUE THREAD

**Issue by tony77682** [elmerfdz/unRAIDscripts#50]
Hello,

Is it possible to be able to send notifications from GOTIFY?
Can you add the CURL package?

thank you

**Comment by elmerfds** [comment]
@tony77682 Please test and let me know if it works for you.

![image](https://user-images.githubusercontent.com/22656503/109398840-28d2d500-7937-11eb-8131-f449906976bc.png)


add the following variables
gotify_notifications=yes
gotify_url=http://gotify.domain.com/message?token=xxxxx-xxxxxxxxx

**Comment by tony77682** [comment]
Great! it's good for notifications notify
thank you

**Comment by tony77682** [comment]
just to know, do you have a link to have the rebuild-DNDC logo?

**Comment by elmerfds** [comment]
No problem. 

Here you go mate: https://github.com/elmerfdz/rebuild-dndc/blob/master/Rebuild-DNDC/img/rdndc-logo.png

**Comment by tony77682** [comment]
thank!
