### ISSUE TITLE
MASTER container ENDPOINTID DOESN'T MATCH

### ISSUE THREAD

**Issue by ps-kl** [elmerfdz/unRAIDscripts#52]
VPN Container restarts on every run because MASTER container ENDPOINTID DOESN'T MATCH.
But the VPN Container is connected. I deleted all Containers and also the docker network.
Also deleted the content of /config/rebuild-dndc. And rebuild VPN Container, Docker Network and the Rebuild-DNDC Container. 

- Starting CRON service now...

---------------------------------
Rebuild-DNDC v4.0.7-u
---------------------------------

-----------------------------------------------------------------------------------
# MASTER CONTAINER INFO
- CONTAINER-NAME: nordvpn
- ENDPOINT-ID: 644bcd8d219d54acf9ab0c104e3e4438a76f9e6355eecca7cc3ac3ff28d4f04d
- NETMODE-ID: 464b6a7917df64e049cfeb6580165874bf3f3e96cb7656ab5270f41988a7e3e3
- CONNECTIVITY: BROKEN
---- restarting nordvpn container
---- nordvpn restarted
---- going to sleep for 10 seconds
-----------------------------------------------------------------------------------

A. SKIPPING: FIRST RUN SETUP
B. ALERT: MASTER container ENDPOINTID DOESN'T MATCH
- REBUILDING: nordvpn container ENDPOINTID DOESN'T MATCH

C. DETECTING: IN-SCOPE CONTAINERS

# RESULTS: None in-scope, checking for previous in-scope containers

- No containers in scope.
- Make sure you have the containers routed through the MASTER container are running fine first.

--------------------------------------------
Run Completed: Sun Apr 4 10:25:00 CEST 2021
--------------------------------------------

**Comment by elmerfds** [comment]
Try the following:
1. Make sure your nordvpn container is the first one that starts, so move it to the top of your container list 
2. Make sure your vpn container is working fine i.e. it has WAN access
3. Move the Rebuild-DNDC container to the bottom of your container list.

You're getting the "CONNECTIVITY: BROKEN" error because your VPN container doesn't have WAN access or it's set to start after the Rebuild container.

**Comment by ps-kl** [comment]
VPN Container Starts First and is Connected.
Added a few Other Containers to the docker Network routing through vpn Container and everything work as it should.

I am not sure whats the Problem.
May something is wrong With the new Build of the nordvpn Image.

Do you may have further hints to workarround?

Thx

**Comment by elmerfds** [comment]
ok, stop the rebuild container, remove any containers that are using the VPN container network. Restart your nordvpn container, monitor the container logs and see if it's stable i.e. it's not randomly restarting or if there are any connection errors.

Once it's connected and it's looking good, run the following command on your unraid terminal and see if you're getting a ping back

`docker exec nordvpn ping -c 20 1.1.1.1`  this is basically the command rebuild is using to determine if the vpn container has internet connectivity or not (CONNECTIVITY: BROKEN test)

Edit: Also what "network type" have you set the rebuild-container to?

**Comment by ps-kl** [comment]
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"ping\": executable file not found in $PATH": unknown

seems the NordVPN container could not use command ping right ?

I guess need to add apt-get install iputils-ping to NordVPN image could that be possible?

at the moment rebuild container network is in bridge mode

thx for help

**Comment by elmerfds** [comment]
Yea! doesn't seem like the iputils-ping package is installed. You could ask the image maintainer to add that. In the mean time you could try disabling the master container connection check on the Rebuild container, set the 'mastercontconcheck' variable to no, see if that works.

or you could switch to a different vpn container that supports NordVPN like https://github.com/qdm12/gluetun

**Comment by ps-kl** [comment]
opened a feature request to add iputils-ping.
Thanks a. lot.
stay healthy
