### ISSUE TITLE
ALERT: MASTER container ENDPOINTID DOESN'T MATCH

### ISSUE THREAD

**Issue by djjoakim** [elmerfdz/unRAIDscripts#54]
Hey!

I have been struggeling to get this working for a bit now, i have read every forum thread i know about this but i just can't get my brain to work it out... On one hand, it seems like it's working - but on the other hand it gives me an error?
I have tried both creating a network and assigning the dockers to that network, and i have also tested the --net command method.
The Rebuild docker is at the bottom of my list, and i make sure it starts the last, it uses bridge to connect.
But still, it get this message in the log... 

-----------------------------------------------------------------------------------
# MASTER CONTAINER INFO
- CONTAINER-NAME: openvpnpublic
- ENDPOINT-ID: 22d26e3ab919ef166b5d73353e98a57447efe0cf39a7dcd361e8351a82790d90
- NETMODE-ID: 98c22bc70a562f62d6b9fb7cea5a1cc906747e391a919bca49675ac7fbcb6a06
- CONNECTIVITY: OK
-----------------------------------------------------------------------------------

A. SKIPPING: FIRST RUN SETUP
B. ALERT: MASTER container ENDPOINTID DOESN'T MATCH
- REBUILDING: openvpnpublic container ENDPOINTID DOESN'T MATCH

C. DETECTING: IN-SCOPE CONTAINERS

# RESULTS: None in-scope, checking for previous in-scope containers

- No containers in scope.
- Make sure you have the containers routed through the MASTER container are running fine first.

--------------------------------------------
Run Completed: Sun Aug 29 12:47:36 CEST 2021
--------------------------------------------

- Starting CRON service now...

Also, is it possible to get this working with multiple VPN dockers? 
And, is there somehow possible to make this restart all the vpn dockers connected to it? Like if the vpn docker crashes and restarts - can it wait 20sec and then restart the dockers that are in the same network?

Thanks!

**Comment by elmerfds** [comment]
REBUILDING: **openvpnpublic** container ENDPOINTID DOESN'T MATCH

You will see this error mention your VPN container name only when you've added your VPN (master) container to the VPN network you've created for your VPN network dependent containers. 

So, change the 'network type' of your  openvpnpublic container to bridge or host.

**Comment by elmerfds** [comment]
Also, before doing the above, do the following:
1. Stop Rebuild-DNDC container
2. Delete all the .tmp files in /config/rebuild-dndc/
3.  Do the steps from my previous comment and make sure your VPN container has established the connection
4.  Start Rebuild-DNDC

Seems like your issue is similar to #49

**Comment by djjoakim** [comment]
> REBUILDING: **openvpnpublic** container ENDPOINTID DOESN'T MATCH
> 
> You will see this error mention your VPN container name only when you've added your VPN (master) container to the VPN network you've created for your VPN network dependent containers.
> 
> So, change the 'network type' of your openvpnpublic container to bridge or host.

Hey!
Thanks for replying. 
Maybe i wasn't clear in my text, but both my vpn and rebuild dndc containers run as bridge. I have had this setup for 1 year and it has been working fine, so i just wan't to "import" Rebuild-DNDC into my system.

**Comment by djjoakim** [comment]
> Also, before doing the above, do the following:
> 
> 1. Stop Rebuild-DNDC container
> 2. Delete all the .tmp files in /config/rebuild-dndc/
> 3. Do the steps from my previous comment and make sure your VPN container has established the connection
> 4. Start Rebuild-DNDC
> 
> Seems like your issue is similar to #49

Well, i shut down the Rebuild-DNDC and deleted all the .tmp files, started vpn and make sure it was running, and then restarted my Rebuild-DNDC docker, now the docker showed up in the logs - but then it went bananas and deleted all my dockers in that network.................. With the same error on every one

/usr/bin/docker: Error response from daemon: Container cannot be connected to network endpoints: container:openvpnpublic, none.

and then 

Error: No such container: organizrv2 (_Well no, bc you deleted it...... :(_)

So now i have to re-install all my dockers again..
Any suggestions?

Thanks!

**Comment by djjoakim** [comment]
Okey so... when i changed it to a network instead of the "--net container bla bla bla" extra parameter stuff, it seems to work fine.. Maybe it's not supported to run like that? I saw an thread on unraid forums with some other guy having the same issue and solved it with that aswell.
Now my log looks like this, is this fine?

Also, does it work like i guess it does? When vpn is down it restarts the vpn container to connect again, but does it also restart the dockers in the same network? Since i have one docker that need to restart when internet is lost, to be connected again..

Thank you once more!

---------------------------------
Rebuild-DNDC v4.0.7-u
---------------------------------

-----------------------------------------------------------------------------------
# MASTER CONTAINER INFO
- CONTAINER-NAME: openvpnpublictest
- ENDPOINT-ID: d1ec88fe0dba26585e6eb9cd977674c5e2d0f87ca9a88603c0212246232db1e6
- NETMODE-ID: b06a028564bd2b0f5a4d1c0e9ccfe7c62b3688dad45069d217f4e5f4168ff9b1
- CONNECTIVITY: OK
-----------------------------------------------------------------------------------

A. SKIPPING: FIRST RUN SETUP
B. SKIPPING: MASTER CONTAINER ENDPOINTID IS CURRENT
C. DETECTING: IN-SCOPE CONTAINERS

1.organizrv2
- ContainerID bf5c5cadad85
- NetworkID: b06a028564bd2b0f5a4d1c0e9ccfe7c62b3688dad45069d217f4e5f4168ff9b1
- Template Location: /config/docker-templates/my-organizrv2.xml

D. PROCESSING: IN-SCOPE CONTAINERS

- SKIPPING: organizrv2 NETID = MASTER NETID

--------------------------------------------
Run Completed: Mon Aug 30 20:00:00 CEST 2021
--------------------------------------------

**Comment by elmerfds** [comment]
Glad you figured it out. Yes! your log looks fine now.  

My preferred method is via the 'Network Type' method but I've also tried `--net=container:vpn_container_name` and it worked fine for me but I'm on Unraid v6.9.1, so not sure if something changed in the newer version.

And yes, this container works exactly as you've described there. It will restart any containers that are using the **master** container's network.

**Comment by elmerfds** [comment]
Currently, it's not possible to monitor multiple VPN container networks but you can spin up multiple instances of the Rebuild-DNDC container and monitor other VPN containers.

**Comment by djjoakim** [comment]
Awesome! Thank you so much for this docker and for the awesome support you have.
You simply are the best! 

I did add a multiple instance of the docker, but then i discovered that it just wen't "Broken" with connection, after trying to ping the vpn docker - i found out that it wasn't possible, so i have asked the creator to add the ping - package to the docker, for now i just set it to "no" in Rebuild-DNDC settings to check the master docker.

Thank you once again for this awesome docker, this will help me so much since i used to restart all the dockers manually, once every week..

Thanks! :D
