### ISSUE TITLE
Container set as network 'None' in Unraid Template error

### ISSUE THREAD

**Issue by kevhardy** [elmerfdz/unRAIDscripts#65]
Not sure if this is intended behavior but I'll report anyway incase it isn't. It appears that the docker run command adds `--net="none"` when you have the Network set as `None` even if there is a manually set `--net` command in the extra parameters field. This causes docker to throw an error. Here is a example using gluetunvpn (I removed some parameter info from logs):

```
/usr/bin/docker run -d --name="app_name" --net="none" (*removed other parameters*) --network=container:gluetunvpn lscr.io/linuxserver/bazarr
/usr/bin/docker: Error response from daemon: Container cannot be connected to network endpoints: container:gluetunvpn, none.
```

Currently my workaround is either to create a manual docker network or set the network to bridge. This run does appear it would work as long as `--net="none"` is omitted when a `--net` command exists in the extra parameters

Unraid Version 6.11.5

**Comment by elmerfds** [comment]
@kevhardy pull the latest image, @olayonjavier 's fix should sort this out now
